//! What a generated remote form knows about itself.
//!
//! The Host's half of the contract in `packages/contracts/src/form-payload.ts`.
//! Architecture rules section 7 lists the immutable metadata every generated
//! form carries; ADR-0021 decision 4 adds the participant's existing note so a
//! remote submission is an *edit* rather than a silent rewrite.
//!
//! Eleven fields, and the shape is frozen. A twelfth is added by amending the
//! decision record, not by widening this struct.
//!
//! # Nothing here is a credential
//!
//! No join token, no session token, no token hash, no join URL, no port, no
//! host address (architecture rules section 20, ADR-0021 decision 3). The type
//! has nowhere to put one, which is a stronger guarantee than remembering not
//! to; [`crate::verify_artifact`] checks the generated bytes anyway.
//!
//! # Dates and times are strings here
//!
//! `meeting_date` and `generated_at` arrive already rendered by
//! `app_core::time`, in the canonical storage forms that cross every other
//! boundary in this application (ADR-0011). This struct is a wire shape, so it
//! carries what goes on the wire; the Host holds the typed values and converts
//! at the edge.

use app_core::id::{MeetingId, ParticipantId, SubmissionId};
use serde::{Deserialize, Serialize};

/// The submission schema version this build generates and accepts.
///
/// Must equal `SUBMISSION_SCHEMA_VERSION` in `packages/contracts`. A test over
/// the shared fixtures fails if the two ever disagree (PRD section 11).
pub const SCHEMA_VERSION: u32 = 1;

/// The payload baked into a generated remote form.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RemoteFormContext {
    /// Always [`SCHEMA_VERSION`].
    pub schema_version: u32,

    /// Identity of **this generated artefact**, minted by the Host as a UUIDv7.
    ///
    /// The form returns it unchanged and never mints one. Generating a second
    /// form for the same participant produces a different `submission_id`, and
    /// both remain importable (ADR-0021 decisions 7 and 13).
    pub submission_id: SubmissionId,

    pub meeting_id: MeetingId,
    pub meeting_title: String,

    /// `YYYY-MM-DD`, meaningless without `meeting_timezone` - which is why the
    /// two always travel together (ADR-0005, PRD section 25.2).
    pub meeting_date: String,
    /// An IANA identifier, for example `Asia/Makassar`.
    pub meeting_timezone: String,

    pub participant_id: ParticipantId,
    pub participant_name: String,

    /// The note version current on the Host at generation, or `0` for none.
    ///
    /// **Advisory only** (ADR-0021 decision 9). It is shown to the Host during
    /// the import preview and blocks nothing; this is not optimistic
    /// concurrency, which ADR-0019 decision 10 declined for every write path.
    pub source_version: i64,

    /// The participant's note as it stood at generation, or `""`.
    ///
    /// GFM-subset Markdown (ADR-0007), and editable form state - never an
    /// authorization source, never an identity source, never evidence.
    pub existing_content: String,

    /// When the Host generated this artefact. The Host's clock, and trusted.
    pub generated_at: String,
}
