//! The persistence port.
//!
//! `app-core` owns the rules and must not own SQL, but the rules can only be
//! enforced against current database state inside the mutating transaction
//! (architecture rules section 15). These traits are the seam: the domain
//! describes what it needs, `app-db` supplies it, and neither knows the other's
//! internals. `app-core` has no SQLite dependency as a result.
//!
//! # Reads and writes are not symmetric
//!
//! Read methods are free to call. Every **write** method takes an
//! [`Authorized`], which only [`crate::authz::authorize`] can produce. The
//! adapter implementing these methods cannot construct one, and neither can a
//! transport. That is what makes the mutation boundary hard to bypass by
//! accident rather than merely by convention.

use crate::audit::AuditEntry;
use crate::authz::Authorized;
use crate::error::DomainResult;
use crate::id::SessionId;
use crate::id::{MeetingId, NoteId, NoteVersionId, ParticipantId};
use crate::meeting::{Meeting, MeetingConfiguration, MeetingStatus};
use crate::participant::ParticipantDetails;
use crate::session::SessionBinding;
use crate::time::UtcTimestamp;
use crate::token::TokenHash;

/// A meeting that does not exist yet.
///
/// Carries no id: the adapter takes it from the [`Authorized`] passed alongside,
/// so the row cannot be written under an id the actor was not authorized for.
/// `status` is supplied by the domain rather than chosen by the adapter, because
/// "a new meeting starts in `DRAFT`" is a business rule and persistence holds
/// none.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewMeeting {
    pub configuration: MeetingConfiguration,
    pub status: MeetingStatus,
    pub at: UtcTimestamp,
}

/// A participant that does not exist yet.
///
/// As with [`NewMeeting`], the meeting id comes from the proof and not from
/// here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewParticipant {
    pub id: ParticipantId,
    pub details: ParticipantDetails,
    pub at: UtcTimestamp,
}

/// A participant of a meeting, as stored.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParticipantRow {
    pub id: ParticipantId,
    pub details: ParticipantDetails,
}

/// A session that does not exist yet.
///
/// Carries only the **hash** of the session token. The token itself is
/// generated by the transport, returned to the browser once, and never travels
/// through this port - a write method that cannot be handed a secret cannot
/// persist one by accident (PRD 22.17, ADR-0002 rule 7).
///
/// `approved_at` is deliberately absent: a new session starts unacknowledged
/// and is fully able to act regardless (ADR-0016).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewSession {
    pub id: SessionId,
    pub participant_id: ParticipantId,
    pub token_hash: TokenHash,
    pub at: UtcTimestamp,
}

/// A participant's current note, as stored.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NoteRow {
    pub id: NoteId,
    pub content: String,
}

/// A note that does not exist yet.
///
/// Carries no meeting id on purpose: the adapter takes it from the
/// [`Authorized`] passed alongside, so a note cannot be written into a meeting
/// the actor was not authorized for even if the payload said otherwise.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewNote {
    pub id: NoteId,
    pub participant_id: ParticipantId,
    pub content: String,
    pub at: UtcTimestamp,
}

/// One row of note history.
///
/// `version` is computed by the domain from current state inside the
/// transaction; a caller never chooses it (ADR-0003, architecture rules 18.1).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewNoteVersion {
    pub id: NoteVersionId,
    pub note_id: NoteId,
    pub version: i64,
    pub content: String,
    pub at: UtcTimestamp,
}

/// Everything the domain can do to the database within one transaction.
///
/// Implementations contain persistence mechanics only. They must not decide
/// authorization, re-check the meeting lock, or interpret business rules: those
/// decisions have already been made by the time an [`Authorized`] exists.
pub trait DomainTx {
    /// Load a meeting's current lifecycle state.
    ///
    /// Called inside the mutating transaction, every time. The returned
    /// [`Meeting`] is the only state a mutation may be judged against.
    fn find_meeting(&self, meeting_id: MeetingId) -> DomainResult<Option<Meeting>>;

    /// This meeting's participant, if they belong to it.
    ///
    /// Scoped by meeting: a participant of another meeting is reported as
    /// absent, which is the same fact from the caller's point of view and does
    /// not leak the existence of other rosters.
    fn find_participant(
        &self,
        meeting_id: MeetingId,
        participant_id: ParticipantId,
    ) -> DomainResult<Option<ParticipantRow>>;

    /// The live session holding this identity, if one does.
    ///
    /// "Live" means `revoked_at IS NULL`. Acknowledged or not, a live session
    /// holds the identity: that is what first-claim-wins means (ADR-0016).
    ///
    /// Read inside the mutating transaction, so a claim is judged against
    /// committed state. The partial unique index is the backstop that decides a
    /// race this read cannot see (ADR-0002).
    fn find_live_session(
        &self,
        meeting_id: MeetingId,
        participant_id: ParticipantId,
    ) -> DomainResult<Option<SessionBinding>>;

    /// How many participants the meeting currently has.
    ///
    /// Read inside the mutating transaction, so the 99-participant limit is
    /// judged against committed state rather than a count a UI remembers
    /// (PRD section 7, architecture rules section 15).
    fn count_participants(&self, meeting_id: MeetingId) -> DomainResult<i64>;

    /// The participant's single note, if they have written one (ADR-0003).
    fn find_note(
        &self,
        meeting_id: MeetingId,
        participant_id: ParticipantId,
    ) -> DomainResult<Option<NoteRow>>;

    /// The highest version recorded for a note, or 0 when it has no history.
    ///
    /// Read inside the transaction so the next version is derived from current
    /// state. The database additionally holds `UNIQUE(note_id, version)`, so a
    /// lost race cannot produce two rows with the same number.
    fn latest_note_version(&self, note_id: NoteId) -> DomainResult<i64>;

    /// Insert a new meeting.
    fn insert_meeting(&self, proof: &Authorized, meeting: &NewMeeting) -> DomainResult<()>;

    /// Replace a meeting's configuration, leaving its lifecycle status alone.
    fn update_meeting_configuration(
        &self,
        proof: &Authorized,
        configuration: &MeetingConfiguration,
        at: UtcTimestamp,
    ) -> DomainResult<()>;

    /// Add a participant to the authorized meeting's roster.
    fn insert_participant(
        &self,
        proof: &Authorized,
        participant: &NewParticipant,
    ) -> DomainResult<()>;

    /// Replace a participant's details.
    ///
    /// `participants` has no `updated_at` column, so the time of the change is
    /// recorded by the audit entry written in the same transaction.
    fn update_participant(
        &self,
        proof: &Authorized,
        participant_id: ParticipantId,
        details: &ParticipantDetails,
    ) -> DomainResult<()>;

    /// Remove a participant from the authorized meeting's roster.
    fn delete_participant(
        &self,
        proof: &Authorized,
        participant_id: ParticipantId,
    ) -> DomainResult<()>;

    /// Replace a meeting's join token hash.
    ///
    /// Overwrites any previous value, which is what makes issuing a new token
    /// invalidate the old URL: the old hash no longer matches anything, so the
    /// old token resolves to no meeting (ADR-0016).
    fn set_join_token_hash(
        &self,
        proof: &Authorized,
        token_hash: &TokenHash,
        at: UtcTimestamp,
    ) -> DomainResult<()>;

    /// Bind an identity to a new session.
    fn insert_session(&self, proof: &Authorized, session: &NewSession) -> DomainResult<()>;

    /// Record that the Host acknowledged a claim.
    ///
    /// Sets `approved_at` and nothing else. It grants no authority the session
    /// did not already have (ADR-0016).
    fn approve_session(
        &self,
        proof: &Authorized,
        session_id: SessionId,
        at: UtcTimestamp,
    ) -> DomainResult<()>;

    /// End a session, freeing the identity to be claimed again.
    ///
    /// Sets `revoked_at`. The row is kept: session history is not deleted, and
    /// the partial unique index only constrains rows where `revoked_at IS NULL`.
    fn revoke_session(
        &self,
        proof: &Authorized,
        session_id: SessionId,
        at: UtcTimestamp,
    ) -> DomainResult<()>;

    /// Set a meeting's lifecycle status, and its `locked_at` when locking.
    fn set_meeting_status(
        &self,
        proof: &Authorized,
        status: MeetingStatus,
        at: UtcTimestamp,
    ) -> DomainResult<()>;

    /// Insert a participant's first note.
    fn insert_note(&self, proof: &Authorized, note: &NewNote) -> DomainResult<()>;

    /// Replace an existing note's content.
    fn update_note_content(
        &self,
        proof: &Authorized,
        note_id: NoteId,
        content: &str,
        at: UtcTimestamp,
    ) -> DomainResult<()>;

    /// Append a row to a note's history.
    fn insert_note_version(&self, proof: &Authorized, version: &NewNoteVersion)
        -> DomainResult<()>;

    /// Append an audit record, attributed to the actor in `proof`.
    fn insert_audit(&self, proof: &Authorized, entry: &AuditEntry) -> DomainResult<()>;
}

/// A database the domain can open a write transaction against.
///
/// The transaction is `BEGIN IMMEDIATE`: it takes the write lock up front, so
/// the state a mutation reads cannot be changed by another writer before it
/// commits. `f` returning `Err` rolls the whole transaction back, which is what
/// makes "a failed mutation leaves no audit record" true by construction rather
/// than by discipline.
pub trait Database {
    /// Run `f` inside exactly one write transaction.
    ///
    /// Takes `&mut dyn FnMut` rather than a generic closure so the trait stays
    /// object-safe; the domain services wrap this in a typed API.
    fn transaction(&self, f: &mut dyn FnMut(&dyn DomainTx) -> DomainResult<()>)
        -> DomainResult<()>;
}

/// So a shared handle can back the mutation boundary.
///
/// A Host application keeps one database for the lifetime of the process and
/// shares it with the Tauri command layer and the LAN server; both hold the
/// same [`crate::service::Domain`] through an `Arc`.
impl<T: Database + ?Sized> Database for std::sync::Arc<T> {
    fn transaction(
        &self,
        f: &mut dyn FnMut(&dyn DomainTx) -> DomainResult<()>,
    ) -> DomainResult<()> {
        (**self).transaction(f)
    }
}
